version: "3.9"

services:
  trashtag_website:
    image: erwanndavid/trashtag_website_v2:latest
    restart: unless-stopped
    hostname: trashtag.io
    networks:
      - caddy
    labels:
        caddy: trashtag.io
        caddy.reverse_proxy: "{{upstreams http 80}}"


networks:
  caddy:
    external: true
